name: "Publish MKP builder"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'mkp-builder/**'
      - '.github/workflows/publish_mkp_builder.yml'

jobs:
  publish-mkp-builder:
    name: Publish MKP builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: ./mkp-builder
          file: ./mkp-builder/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # this is a simple tool that really does not not need proper versioning
          tags: |
            ghcr.io/pagopa/checkmk-mkp:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
